[package]
name = "webgpu-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu", branch = "trunk" }
env_logger = "0.10"
thiserror = "1.0.50"
bytemuck = "1.14.0"
pollster = "0.2.4"
rand = "0.8.5"