name: Build quartz
description: ""
inputs:
  content_path:
    description: the content path
    required: true
  output_path:
    description: the output path
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3

    - uses: actions/checkout@v3
      with:
        repository: jackyzha0/quartz
        ref: v4
        path: quartz

    - name: copy content
      shell: bash
      run: cp -r ${{ inputs.content_path }}/ quartz/content/

    - name: Build quartz
      shell: bash
      run: |
        cd quartz
        npm install
        npx quartz build
        ls -la quartz/public/**

    - name: Copy output
      shell: bash
      run: cp -r quartz/public/** ${{ inputs.output_path }}/
