[project]
name = "nn"
version = "0.1.0"
description = "Add a short description here"
authors = ["Li Yazhou <me.ssword@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[commands]
pip = "python -m pip install -r requirements.txt"
test = "python -m unittest discover . '*_test.py'"
fmt = "black ."

[dependencies]
python = "3.11.4.*"
black = "23.3.0.*"
pip = "23.1.2.*"
