# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://qiita.com/kjtanaka/items/f16757c1f0cc86ff225b

Vagrant.require_version ">= 1.5.0"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_version = '8.2'
  config.vm.define "vagrant-lln01" do |dev|
    dev.vm.network "private_network", ip: "192.168.33.10"

    dev.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end

    dev.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get -y install bridge-utils
    SHELL
  end
end
